# Generated by Django 4.1.7 on 2023-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player_Characters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CharacterName", models.TextField()),
                (
                    "Race",
                    models.CharField(
                        choices=[
                            ("Human", "human"),
                            ("Elf", "elf"),
                            ("Dwarf", "dwarf"),
                            ("Hafling", "hafling"),
                            ("Half-Elf", "halfelf"),
                            ("Half-Orc", "halforc"),
                            ("Orc", "orc"),
                            ("Gnome", "gnome"),
                            ("Tiefling", "tiefling"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "Class",
                    models.CharField(
                        choices=[
                            ("Fighter", "fighter"),
                            ("Wizard", "wizard"),
                            ("Rogue", "rogue"),
                            ("Cleric", "cleric"),
                            ("Barbarian", "barbarian"),
                            ("Bard", "bard"),
                            ("Druid", "druid"),
                            ("Monk", "monk"),
                            ("Paladin", "paladin"),
                            ("Ranger", "ranger"),
                            ("Sorcerer", "sorcerer"),
                            ("Warlock", "warlock"),
                        ],
                        max_length=30,
                    ),
                ),
                ("Strength", models.IntegerField()),
                ("Dexterity", models.IntegerField()),
                ("Constitution", models.IntegerField()),
                ("Intelligence", models.IntegerField()),
                ("Wisdom", models.IntegerField()),
                ("Charisma", models.IntegerField()),
                ("Skills", models.TextField()),
                ("Background", models.TextField()),
                ("Equipment", models.TextField()),
                ("Spells", models.TextField()),
                ("Appearance", models.TextField()),
                ("PersonalityTraits", models.TextField()),
                ("DateCreated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
