# Generated by Django 4.1.7 on 2023-05-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_id"),
        ("characters", "0002_alter_player_characters_charactername"),
    ]

    operations = [
        migrations.AddField(
            model_name="player_characters",
            name="UserID",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.userprofile",
            ),
        ),
    ]
